### ISSUE TITLE
Include the available date in the info hash so I can sort by date in the queue.

### ISSUE THREAD

**Issue by evaryont** [Yoshiofthewire/CrunchyXBMC#19]
While not 100% analogous (entirely possible that the episode is uploaded to Crunchyroll late, or is only now being made available digitally) I think it should work well enough. Think it should be something along expanding the dict for `add_item()`, like on [line 739](https://github.com/Yoshiofthewire/CrunchyXBMC/blob/master/resources/lib/crunchy_json.py#L739).

**Comment by Yoshiofthewire** [comment]
Kodi has to support the info being placed in, so since Kodi doesn't support this, there isn't a place to put it.  That some where along the way sorting was strait up broken doesn't help.
