### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by TheHolyDevil** [Yoshiofthewire/CrunchyXBMC#2]
when trying to enter menues with anime like popular simulcasts updated and so on i get Error - Script error crunchyroll;xbmc

and cant get into those menues

**Comment by Yoshiofthewire** [comment]
In theory this is resolved.
Closing

**Comment by earithramir** [comment]
Hi, 

on version 2.2 i've had the same issue
this was resolved by deleting serdata/addon_data/plugin.video.crunchyroll-takeout/cruchyPickle
I've now created a cronjob to delete this folder every day, but i think it should be better to have the plugin do this, right?

**Comment by Yoshiofthewire** [comment]
When the file is deleted it causes a new UUID to be created, and a new UUID is added to the client's Crunchyroll profile.  So it would be bad form to do that.  In theory the plugin should do that itself when it detects an issue ... but then so should the Crunchyroll and VRV Android Apps.
