### ISSUE TITLE
Login isn't working

### ISSUE THREAD

**Issue by tamodolo** [Yoshiofthewire/CrunchyXBMC#24]
today my loggin info started to be rejected. On official app it works properly (tested after this issue on ps4, webbrowser and android)

The log for this issue:

11:32:51 T:5828  NOTICE: CR: Starting new session
11:32:51 T:5828  NOTICE: CR: makeAPIRequest: get JSON
11:32:51 T:5828  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/start_session.0.json
11:32:51 T:5828  NOTICE: CR: makeAPIRequest: options = locale=ptBR&access_token=S7zg3vKx6tRZ0Sf&version=1.0.1&device_type=com.crunchyroll.ps3&device_id=ozlKLd6FaGiABmeZpQCHj7IDfJv2sEX9
11:32:52 T:4636   DEBUG: ------ Window Init (DialogBusy.xml) ------
11:32:52 T:5828   DEBUG: CR: makeAPIRequest: reply =
11:32:52 T:5828   DEBUG:   message
11:32:52 T:5828   DEBUG:     Unauthenticated request
11:32:52 T:5828   DEBUG:   code
11:32:52 T:5828   DEBUG:     bad_auth_params
11:32:52 T:5828   DEBUG:   error
11:32:52 T:5828   DEBUG:     True
11:32:52 T:5828   ERROR: CR: Error starting new session. Error message: Unauthenticated request

Please update the version on kodi repo too

**Comment by Yoshiofthewire** [comment]
fixed 2.1.2
