### ISSUE TITLE
Sorting is inconsistent.

### ISSUE THREAD

**Issue by saeraphas** [Yoshiofthewire/CrunchyXBMC#26]
Sorting methods vary from show to show between ascending and descending, and the option to change sort methods is disabled. 

For example, Fate/Zero season list is sorted descending, but Seasons 1 and 2 are sorted ascending. 
Fate/Stay Night episodes are sorted descending.

Can there be a toggle somewhere to set a default sort method for the addon?

**Comment by Yoshiofthewire** [comment]
The sorting is based on if the show is marked complete by Crunchyroll.
If the show is completed, it is showed in ascending order, to make simpler to navigate in one sitting.
If the show is not, it is in descending, so you don't have to scroll the whole list to get to a new episode.
I did not know that choosing ascending for descending doesn't work.
The plugin is passing Episode Numbers, so I have no idea why it won't sort.
