### ISSUE TITLE
small cut on episode start

### ISSUE THREAD

**Issue by schmurfy** [Yoshiofthewire/CrunchyXBMC#28]
That is a bad title but I don't really know how to describe that in one sentence xD
What I see is that everytime I start playing an episode (from my Queue) it starts playing fine for a few seconds and then the screen goes black and playback comes back but after a few seconds have been skipped.

That is not a huge issue but that is quite weird, other videos play fine and so far that is the only addon on which I see this behavior, any idea what might be causing it ?

Edit: I am using Kodi 15 but already had this with the previous version.

**Comment by Yoshiofthewire** [comment]
What are you using Kodi on?
I have not seen this issue.

**Comment by schmurfy** [comment]
in fact I noticed it on every video played by kodi so that's clearly not specific to your addon, that's weird.
I am running it on a mini pc under archlinux installed with the package they build, I will check if there is an error logged somewhere.
