### ISSUE TITLE
Sort in Queue don't respect site sort in version 2.2.1

### ISSUE THREAD

**Issue by tamodolo** [Yoshiofthewire/CrunchyXBMC#34]
until 1.7 queue list respected order defined in the site but now kodi is sorting by alphabetic order. In the sort options there are only ascend and descend by sort type title which is grayed. I don't know if the cause is the plugin or some change in kodi itself.

**Comment by Neogrey** [comment]
Same problem here with 2.2.1 (Raspberry PI 2 + Openelec 5.0.8) , 2.2 works fine.

**Comment by tamodolo** [comment]
Sorry! I forget to add the version that this problem started. Since 2.2 didn't worked for me I was unable to test but it's a problem introduced in 2.2.1. Previous working version for me was 1.7

**Comment by Yoshiofthewire** [comment]
Check the updated 2.2.1.  That should fix it.

**Comment by tamodolo** [comment]
Yes! It's fixed! Thank you very much!
