### ISSUE TITLE
The Addon Doesn't detect VPN

### ISSUE THREAD

**Issue by nishith4C** [Yoshiofthewire/CrunchyXBMC#41]
I have VPNIcity installed for Kodi but the content doesn't match the VPN country.

**Comment by ironashram** [comment]
I'm facing the same issue using ivacy vpn, from browser i can see US catalog but not from xbmc, i still get what i have without VPN.
Tried to delete addon and reinstall/reconfigure it but then fails to auhtenticate 
Session Failed: Check Login
I have to disconnect vpn and then plugin works, but always without getting the US catalog.
PPTP vpn from windows 10

**Comment by ironashram** [comment]
Nevermind after reinstalling the addon(cleaning also the related addons_data folder) with the vpn active and doing the first login it is now working.
