### ISSUE TITLE
Watch status

### ISSUE THREAD

**Issue by Neogrey** [Yoshiofthewire/CrunchyXBMC#43]
Current crunchyroll plugin, with Aeon Nox and Estuary:

![screenshot002](https://cloud.githubusercontent.com/assets/10816058/19219735/0cd35bbe-8e1c-11e6-8e7a-12693bdcc958.png)
![screenshot003](https://cloud.githubusercontent.com/assets/10816058/19219739/1c450494-8e1c-11e6-8781-9b7e9dd39487.png)
(Add Artwork on the left side ? )

I think something like the funimationnow plugin watch status , perhaps this is a better solution ?: https://github.com/Protocol-X/plugin.video.funimationnow
![screenshot005](https://cloud.githubusercontent.com/assets/10816058/19219773/bed1c094-8e1c-11e6-8a63-60023c670ee3.png)
![screenshot004](https://cloud.githubusercontent.com/assets/10816058/19219774/c3308e4a-8e1c-11e6-9ad1-9998f29eecbb.png)

**Comment by Enigma0** [comment]
I think both would be good - or a setting in the addon to choose between which/both.

**Comment by Neogrey** [comment]
Thanks, looks good.

It would be great, a setting to disable percent/watch status after the anime titel
my  quick & dirty solution: change `infoLabels = {"Title":   info['title'] + percentPlayed,` to `infoLabels = {"Title":   info['title'],`
