### ISSUE TITLE
Duration Information displayed incorrectly (possible Kodi API bug)

### ISSUE THREAD

**Issue by lrenaud** [Yoshiofthewire/CrunchyXBMC#46]
### Summary:

Upon loading videos they display incorrect duration information. This results in odd seeking behavior near the end of an show/video, or broken resume behavior if the seek time is after the incorrect video duration.
### Steps to reproduce:
1. Start playback of new video.
2. Pause video to check end time.
### Expected behavior:

Time should reflect the length of the episode matching the API returned value of args.duration inside the start_payback() routine in the plugin source, or the same time reflected on the Crunchyroll web site flash player.
### Observed behavior:

Duration of video is usually some slightly smaller time off by some unknown time. I've seen it as small as 20-30 seconds, and in excess of 1 minute all on roughly 23 minute shows.

It looks like the duration information is assigned to the initial setup in the start_playback() routine of crunchy_json.py. I'm looking at `item.setProperty('TotalTime',  args.duration)` on line 1120. Calling a item.getProperty('TotalTime') or item.getProperty('Duration') return the expected value, but later on calling `player.getTotalTime()` after the player starts (in my case I inserted a test line at line 1100) will return the incorrect value that is being used by the GUI.

It's not clear to me if this is simply an implementation bug in the crunchyroll plugin, or a bug in the Kodi/XBMC API.

**Comment by Neogrey** [comment]
I'm not sure, but seems Kodi use the duration from the m3u8 file for the player. 

Example: Gabriel DropOut Episode 5
Duration is ~23:40 
Starting playback (Kodi) and the Duration is ~22:42

Open the m3u8 from Gabriel DropOut Episode 5 with VLC and Duration is only ~22:42. So it's a problem from crunchyroll side, which provide this m3u8.

**Comment by lrenaud** [comment]
Back when this bug was filed I noted that the duration of the file that was set prior to the start of playback is valid but is instantly replaced by a mechanism I couldn't nail down. If the playlist file is where the incorrect duration is coming from, is there anything we can even do to fix this in the plugin or is it baked into a lower level Kodi assumption about the validity of playlist metadata?

**Comment by Neogrey** [comment]
Unfortunately, I have no idea how to fix this.
