### ISSUE TITLE
Can't Login in Xbox One Kodi v18

### ISSUE THREAD

**Issue by ehekuta** [Yoshiofthewire/CrunchyXBMC#77]
I installed the add-on from zip in Kodi v18 in Xbox One and apper a problem with Username and Password, but they are fine.

**Comment by AluminumGriffin** [comment]
From zip as in you downloaded the zip from here on github? Does the error-page state "Login failed" or "Session failed"?
(In case of the former it should remove the pickle by itself, also the "Login Failed" should open the settings-page if you try to activate it)

Anyhow, the normal steps are:

1) Remove the pickle (see issue #44 for this)

2) Re-enter username and password (and remove the pickle again), to really make sure.

3) Visit crunchyroll.com with a javacript enabled browser from the same LAN as the xbox is connected to (this usually only happens to devs, it is the anti-bot check at cloudflare) (try to log in as well, just to verify user/pass)

If it still doesn't work please post logs (kodi.log)

**Comment by ehekuta** [comment]
Thanks! The problem was the pickle, now all works fine.

PD: I installed the plugin from here (github .zip), but the version 2.2.2 of the plugin in Kodi Repository & SuperRepo have a lot of error messages
